# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chungdinh/Code/testSDL2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chungdinh/Code/testSDL2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chungdinh/Code/testSDL2/CMakeFiles /home/chungdinh/Code/testSDL2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chungdinh/Code/testSDL2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDL2Test

# Build rule for target.
SDL2Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2Test
.PHONY : SDL2Test

# fast build rule for target.
SDL2Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/build
.PHONY : SDL2Test/fast

src/Ball/Ball.o: src/Ball/Ball.cpp.o
.PHONY : src/Ball/Ball.o

# target to build an object file
src/Ball/Ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Ball/Ball.cpp.o
.PHONY : src/Ball/Ball.cpp.o

src/Ball/Ball.i: src/Ball/Ball.cpp.i
.PHONY : src/Ball/Ball.i

# target to preprocess a source file
src/Ball/Ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Ball/Ball.cpp.i
.PHONY : src/Ball/Ball.cpp.i

src/Ball/Ball.s: src/Ball/Ball.cpp.s
.PHONY : src/Ball/Ball.s

# target to generate assembly for a file
src/Ball/Ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Ball/Ball.cpp.s
.PHONY : src/Ball/Ball.cpp.s

src/Cannon/Cannon.o: src/Cannon/Cannon.cpp.o
.PHONY : src/Cannon/Cannon.o

# target to build an object file
src/Cannon/Cannon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Cannon/Cannon.cpp.o
.PHONY : src/Cannon/Cannon.cpp.o

src/Cannon/Cannon.i: src/Cannon/Cannon.cpp.i
.PHONY : src/Cannon/Cannon.i

# target to preprocess a source file
src/Cannon/Cannon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Cannon/Cannon.cpp.i
.PHONY : src/Cannon/Cannon.cpp.i

src/Cannon/Cannon.s: src/Cannon/Cannon.cpp.s
.PHONY : src/Cannon/Cannon.s

# target to generate assembly for a file
src/Cannon/Cannon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Cannon/Cannon.cpp.s
.PHONY : src/Cannon/Cannon.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Player/Player.o: src/Player/Player.cpp.o
.PHONY : src/Player/Player.o

# target to build an object file
src/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Player/Player.cpp.o
.PHONY : src/Player/Player.cpp.o

src/Player/Player.i: src/Player/Player.cpp.i
.PHONY : src/Player/Player.i

# target to preprocess a source file
src/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Player/Player.cpp.i
.PHONY : src/Player/Player.cpp.i

src/Player/Player.s: src/Player/Player.cpp.s
.PHONY : src/Player/Player.s

# target to generate assembly for a file
src/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Player/Player.cpp.s
.PHONY : src/Player/Player.cpp.s

src/Stuff/Stuff.o: src/Stuff/Stuff.cpp.o
.PHONY : src/Stuff/Stuff.o

# target to build an object file
src/Stuff/Stuff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Stuff/Stuff.cpp.o
.PHONY : src/Stuff/Stuff.cpp.o

src/Stuff/Stuff.i: src/Stuff/Stuff.cpp.i
.PHONY : src/Stuff/Stuff.i

# target to preprocess a source file
src/Stuff/Stuff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Stuff/Stuff.cpp.i
.PHONY : src/Stuff/Stuff.cpp.i

src/Stuff/Stuff.s: src/Stuff/Stuff.cpp.s
.PHONY : src/Stuff/Stuff.s

# target to generate assembly for a file
src/Stuff/Stuff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Stuff/Stuff.cpp.s
.PHONY : src/Stuff/Stuff.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SDL2Test"
	@echo "... src/Ball/Ball.o"
	@echo "... src/Ball/Ball.i"
	@echo "... src/Ball/Ball.s"
	@echo "... src/Cannon/Cannon.o"
	@echo "... src/Cannon/Cannon.i"
	@echo "... src/Cannon/Cannon.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Player/Player.o"
	@echo "... src/Player/Player.i"
	@echo "... src/Player/Player.s"
	@echo "... src/Stuff/Stuff.o"
	@echo "... src/Stuff/Stuff.i"
	@echo "... src/Stuff/Stuff.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

